services:
  mysql:
    image: mysql:9.6.0
    container_name: fixmyroom-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P@sword1234!
      MYSQL_DATABASE: fixmyroom
      MYSQL_USER: lsupwp
      MYSQL_PASSWORD: P@sword1234!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fixmyroom_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: fixmyroom-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: "P@sword1234!"
      DB_NAME: fixmyroom
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fixmyroom_network

volumes:
  mysql_data:

networks:
  fixmyroom_network:
    driver: bridge
